/*! YAD - v1.0.0 - 861b558 - 2014-08-07
 *  Yahoo Personalised Content Widget
 *  Copyright (c) 2014 ; Licensed  */
(function(){var e=window.document,c={Error:function(a){this.message=a},Bootstrap:function(a,b,f){this.widgetInitialisationStartedAt=this.timeSinceNavigationStart();this.snippetLoadedAt=f?this.timeSinceNavigationStart(f):null;this.config=b;this.publisherId=a;this.config.analytics||(this.config.analytics={});this.id=this.config.id;this.config.analytics.pageURL=this.detectPageURL();this.config.analytics.referrer=this.detectReferrer();this.config.analytics.click_postmsg={payload:{action:"redirect",id:this.id}};
this.config.canonicalURL=this.detectCanonical();this.init()}};c.Bootstrap.prototype={init:function(){this.element="undefined"!==typeof this.config.element?this.config.element:this.detectScriptTag();delete this.config.element;var a=this.iframeURL();this.iframe=this.createIframeElement(a);var b=this;window.addEventListener?this.iframe.addEventListener("load",function(){b.sendPostMessage({action:"init",config:b.config,id:b.id,url:b.detectPageURL(),tti:b.widgetInitialisationStartedAt,tts:b.snippetLoadedAt,
cid:b.publisherId})}):window.attachEvent&&this.iframe.attachEvent("onload",function(){b.sendPostMessage({action:"init",config:b.config,id:b.id,url:b.detectPageURL(),tti:b.widgetInitialisationStartedAt,tts:b.snippetLoadedAt,cid:b.publisherId})});this.listen();this.render()},detectPageURL:function(){return window.location.href},detectReferrer:function(){return window.document.referrer},detectCanonical:function(){var a=e.querySelector("link[rel='canonical']");return a?a.href:!1},listenForViewport:function(){var a=
this,b=null,f=null,d=function(d){return function(){var c=a.isElementInViewport(d,0);c&&!a.hasBeenInViewport&&(a.hasBeenInViewport=!0,a.sendPostMessage({action:"inViewport"}));if(c){var e=function(){var b=a.iframeRelativeScrollPosition(d);a.sendPostMessage({action:"scroll",scrollTop:b[0],scrollLeft:b[1],height:a.iframeRelativeHeight(d),width:a.iframeRelativeWidth(d)})};window.clearTimeout(b);b=window.setTimeout(function(){window.clearInterval(f);e();f=null},350);null===f&&(f=window.setInterval(e,500),
e())}}}(this.iframe);window.addEventListener?(window.addEventListener("DOMContentLoaded",d,!1),window.addEventListener("load",d,!1),window.addEventListener("scroll",d,!1),window.addEventListener("resize",d,!1)):window.attachEvent&&(window.attachEvent("DOMContentLoaded",d),window.attachEvent("onload",d),window.attachEvent("onscroll",d),window.attachEvent("onresize",d));d()},iframeURL:function(){return c.Bootstrap.IFRAME_URL},createIframeElement:function(a){var b=e.createElement("iframe");b.frameBorder=
0;b.width="100%";b.height="0";b.setAttribute("style","display:block");b.setAttribute("src",a);return b},sendPostMessage:function(a){return c.PostMessage.send(a,c.Bootstrap.IFRAME_DOMAIN,this.iframe.contentWindow)},listen:function(){c.PostMessage.listen(this.onReceivePostMessage,c.Bootstrap.IFRAME_DOMAIN,this)},render:function(){this.element.appendChild(this.iframe)},detectScriptTag:function(){var a=e.querySelectorAll("script");if(!a)throw new c.Error("No script tags could be found on the page");return a[a.length-
1]},onReceivePostMessage:function(a){if(a.id===this.id)switch(a.action){case "data":this.listenForViewport();break;case "height":this.setHeight(a.height);break;case "redirect":this.redirect(a.href);break;case "hide":this.hide();break;case "error":this.config.onError&&"function"===typeof this.config.onError&&this.config.onError.apply(this,[Error("widget failed to load")]);break;case "about":c.Lightbox.About()}},hide:function(){this.iframe&&(this.iframe.style.display="none");this.element&&this.element.setAttribute("class",
this.element.getAttribute("class")+" yad-empty")},redirect:function(a){window.location=a},setHeight:function(a){this.iframe.height=a+"px"},isElementInViewport:function(a,b){"undefined"===typeof b&&(b=0);var f,d;"undefined"!==typeof window.pageXOffset?f=window.pageXOffset:e.documentElement&&"undefined"!==typeof e.documentElement.scrollLeft?f=e.documentElement.scrollLeft:"undefined"!==typeof e.body.scrollLeft&&(f=e.body.scrollLeft);"undefined"!==typeof window.pageYOffset?d=window.pageYOffset:e.documentElement&&
"undefined"!==typeof e.documentElement.scrollTop?d=e.documentElement.scrollTop:"undefined"!==typeof e.body.scrollTop&&(d=e.body.scrollTop);var c,g;g=c=0;c="undefined"!==typeof window.innerWidth?window.innerWidth:e.documentElement.clientWidth;g="undefined"!==typeof window.innerHeight?window.innerHeight:e.documentElement.clientHeight;c=f+c;g=d+g;var k=b,h=a.getBoundingClientRect(),l=h.right-h.left,m=h.bottom-h.top,n=h.top+d,h=h.left+f,p,q;p=h+l*(1-k);q=n+m*(1-k);return!(c<h+l*k||f>p||g<n+m*k||d>q)},
iframeRelativeHeight:function(a){var b=a.getBoundingClientRect(),c=b.top,d=window.innerHeight||e.documentElement.clientHeight;a=a.scrollTop;b=b.bottom-b.top;return c<a&&b-a>=d?d:c<a?Math.max(0,b-(a-c)):c>a&&c+b<d?b:Math.max(0,d-(c-a))},iframeRelativeWidth:function(a){var b=a.getBoundingClientRect(),c=b.left,d=window.innerWidth||e.documentElement.clientWidth;a=a.scrollLeft;b=b.right-b.left;return c<a&&b-a>=d?d:c<a?Math.max(0,b-(a-c)):c>a&&c+b<d?b:Math.max(0,d-(c-a))},iframeRelativeScrollPosition:function(a){a=
a.getBoundingClientRect();var b=-1*a.top,c=-1*a.left;0<a.left&&(c=0);0<a.top&&(b=0);return 0>b||0>c?[0,0]:[Math.max(0,b),Math.max(0,c)]},timeSinceNavigationStart:function(a){if("undefined"===typeof window.performance)return!1;a||(a=(new Date).getTime());return a-window.performance.timing.domLoading}};c.PostMessage={lastHeight:null,send:function(a,b,f){if("undefined"===typeof b)throw new c.Error("You must supply a target as a string");"undefined"===typeof f&&(f=window.parent);f.postMessage(c.PostMessage._serialize(a),
b)},listen:function(a,b,f){if("undefined"===typeof b)throw new c.Error("You must supply an origin or an array of origins");var d=function(d){if("*"!==b&&b!==d.origin)return!1;a.call(f,c.PostMessage._unserialize(d.data),d.origin,d.source)};window.addEventListener?window.addEventListener("message",d,!1):window.attachEvent("onmessage",d)},sendHeight:function(a,b,f){c.PostMessage._sendUpdateHeightMessage(a,b,f);window.setInterval(function(){c.PostMessage._sendUpdateHeightMessage(a,b,f)},1E3)},_sendUpdateHeightMessage:function(a,
b,f){var d=Math.max(Math.max(e.body.scrollHeight,e.documentElement.scrollHeight),Math.max(e.body.offsetHeight,e.documentElement.offsetHeight),Math.max(e.body.clientHeight,e.documentElement.clientHeight));c.PostMessage.lastHeight!==d&&(void 0===f&&(f={}),f.action="height",f.height=d,c.PostMessage.send(f,a,b),c.PostMessage.lastHeight=d)},_unserialize:function(a){return JSON.parse(a)},_serialize:function(a){return JSON.stringify(a)}};c.Lightbox=function(){this.init()};c.Lightbox.MASK_STYLE="position:fixed;top:0;left:0;z-index:99999;background-color:#000;background-color:rgba(0,0,0,0.5);width:100%;height:100%;";
c.Lightbox.CONTENT_STYLE='position:relative;margin:0 auto;top:10%;z-index:999999;background-color:#fff;width:100%;min-height:100px;max-height:80%;overflow:auto;width:400px;max-width:90%;border-radius: 5px;box-shadow: 0px 0px 20px 0px rgba(0,0,0,0.55);"';c.Lightbox.CLOSE_STYLE="position:absolute;right:0;top:0;padding:5px;cursor:pointer;text-decoration:none;color: #5f5f5f;line-height: 6px;text-align:center;margin: 6px;font-size: 22px;";c.Lightbox.About=function(){var a=new c.Lightbox;a.setContent("<iframe src='"+
c.Lightbox.ABOUT_IFRAME_URL+"' style='width:100%;height:300px' frameborder='0'></iframe>");a.show();return a};c.Lightbox.prototype={init:function(){this.lightboxContent=""},show:function(){this.exists()?this.container().style.display="block":(this.create(),this.show())},hide:function(){this.exists()&&(this.container().style.display="none")},create:function(){this.createMask();this.createContentPane();this.createCloseButton();this.bindClose()},createMask:function(){var a=e.createElement("div");a.setAttribute("class",
"yad-lightbox");a.setAttribute("style",c.Lightbox.MASK_STYLE);a.style.display="none";e.getElementsByTagName("body")[0].appendChild(a);return this.containerDiv=a},createContentPane:function(){var a=e.createElement("div");a.setAttribute("class","yad-lightbox-content");a.setAttribute("style",c.Lightbox.CONTENT_STYLE);this.container().appendChild(a);this.lightboxContent&&"string"===typeof this.lightboxContent?a.innerHTML=this.lightboxContent:this.lightboxContent&&a.appendChild(this.lightboxContent);return this.contentPane=
a},createCloseButton:function(){var a=e.createElement("a");a.setAttribute("class","yad-lightbox-close");a.setAttribute("style",c.Lightbox.CLOSE_STYLE);a.innerHTML="\u00d7";this.contentPane.appendChild(a);return a},bindClose:function(){var a=this;window.addEventListener?(this.container().addEventListener("click",function(b){b.target===a.container()&&a.closeHandler.call(a)},!1),this.container().querySelector(".yad-lightbox-close").addEventListener("click",function(){a.closeHandler.call(a)}),window.addEventListener("keydown",
function(b){27===b.keyCode&&a.closeHandler.call(a)},!1)):window.attachEvent&&(this.container().attachEvent("onclick",function(b){b.target===a.container()&&a.closeHandler.call(a)},!1),this.container().querySelector(".yad-lightbox-close").attachEvent("onclick",function(){a.closeHandler.call(a)}),window.attachEvent("onkeydown",function(b){27===b.keyCode&&a.closeHandler.call(a)},!1))},closeHandler:function(){this.hide()},container:function(){return this.containerDiv},exists:function(){return!!this.container()},
setContent:function(a){this.lightboxContent=a}};c.Helper=c.Helper||{};c.Helper.Ajax={JSONPCallbacks:{},timeouts:{},AJAX_TIMEOUT:1E3,ajax:function(a,b,f,d,e){return c.Helper.Ajax.jsonp(a,b,f,d,e)},xhr:function(a,b,c,d,e){var g=new XMLHttpRequest;g.onreadystatechange=function(){4>g.readyState||200===g.status&&4===g.readyState&&c.call(e,g)};g.open("GET",a,!0);try{g.send("")}catch(h){"function"===typeof d&&d(h)}},jsonp:function(a,b,f,d,e){var g=(new Date).getTime();b&&(a+=(-1<a.indexOf("?")?"&":"?")+
c.Helper.Ajax.urlencode(b));a=a+(-1<a.indexOf("?")?"&":"?")+"callback="+("YADJSONPCallbacks.receiveCallback_"+g);c.Helper.Ajax.JSONPCallbacks["receiveCallback_"+g]=function(a){window.clearTimeout(c.Helper.Ajax.timeouts[g]);a&&a.error&&d?d.call(e,a):a&&a.error?console.error("JSONP called returned an error, but there was no handler provided."):f&&f.call(e,a);delete c.Helper.Ajax.JSONPCallbacks["receiveCallback_"+g]};b=setTimeout(function(){c.Helper.Ajax.JSONPCallbacks["receiveCallback_"+g]=function(){delete c.Helper.Ajax.JSONPCallbacks["receiveCallback_"+
g]};d&&d.call(e,{error:!0,isTimeout:!0})},c.Helper.Ajax.AJAX_TIMEOUT);c.Helper.Ajax.timeouts[g]=b;c.Helper.Ajax.addScript(a)},createElement:function(a){return e.createElement(a)},addScript:function(a,b,f){var d=c.Helper.Ajax.createElement("script"),h=e.getElementsByTagName("head")[0],g=!1;d.type="text/javascript";d.src=a;b&&(d.onload=d.onreadystatechange=function(){g||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(g=!0,d.onload=d.onreadystatechange=null,b.call(f))});h.insertBefore(d,
h.firstChild)},urlencode:function(a,b){var e=[],d,h,g;for(d in a)if(a.hasOwnProperty(d))switch(h=b&&a instanceof Array?b+"[]":b?b+"["+d+"]":d,g=a[d],typeof g){case "object":e.push(c.Helper.Ajax.urlencode(g,h));break;case "Array":break;default:e.push(encodeURIComponent(h)+"="+encodeURIComponent(g))}return e.join("&")},generateRequestID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"===a?b:b&3|8).toString(16)})}};window.YADJSONPCallbacks=
window.YADJSONPCallbacks||c.Helper.Ajax.JSONPCallbacks;c.Bootstrap.IFRAME_DOMAIN="https://s.yimg.com";c.Bootstrap.LOG_PATH="//syndication.streamads.yahoo.com/na_stream_brewer/error/v1";c.Bootstrap.IFRAME_URL=c.Bootstrap.IFRAME_DOMAIN+"/uq/syndication/yad-iframe.861b558.html";c.Lightbox.ABOUT_IFRAME_URL=c.Bootstrap.IFRAME_DOMAIN+"/uq/syndication/yad-about.html";if("undefined"===typeof window.yad||!window.yad.initialized){var m="undefined"!==typeof window.yad&&"undefined"!==typeof window.yad.q?
window.yad.q:[],l=[],n=c.Helper.Ajax.generateRequestID();window.yad=function(a,b,f){b=b||{};var d=b.debug&&window.console&&window.console.error,h=null;try{b.element||(b.element=e.querySelector(".YAD-"+a));b.element||(b.element=e.querySelectorAll(".YAD")[l.length]);if(!b.element)throw new c.Error("Element with index #"+l.length+" not found");b.id=window.yad.i;b.pageviewID=n;h=new c.Bootstrap(a,b,f);l.push(h);window.yad.i++}catch(g){h&&h.hide();try{c.Helper.Ajax.ajax(c.Bootstrap.LOG_PATH,{exception:g.message,
type:"bootstrap",cid:a,pvid:n,url:window.location&&window.location.href})}catch(k){d&&window.console.error("YAD: Unable to send following message to log due to "+k.message)}if(d)if(g instanceof c.Error)window.console.error("YAD: "+g.message);else throw g;}};window.yad.initialized=!0;window.yad.i=1;for(var h;m&&(h=m.shift());)"string"===typeof h[0]?window.yad(h[0],h[1]):(h[0]instanceof Array||h[0]instanceof Object)&&window.yad(h[0][0],h[0][1],h[1])}c.VERSION="861b558"})();
